services:
  dashboard:
    image: source-dashboard/local
    ports:
      - "4000:4000"
  api:
    image: source-api/local
    ports:
      - "4001:4001"
    expose:
      - 4001
    env_file: "s3.env"
    environment:
      PORT: "4001"
  tusd:
    image: tusproject/tusd:latest
    ports:
      - "8080:8080"
    env_file: "s3.env"

    command:
      [
        -s3-bucket=sourcedev,
        -s3-object-prefix=tusd,
        -hooks-http=http://api:4001/internal/tusd/webhook,
        -cors-allow-origin=http://localhost:4000,
        -cors-allow-headers=X-API-KEY,
      ]
