services:
  dashboard:
    image: source-dashboard/local
    build: ../dashboard
    ports:
      - "4000:4000"
  api:
    image: source-api/local
    build: ../api
    ports:
      - "4001:4001"
    expose:
      - 4001
    env_file: "s3.env"
    environment:
      PORT: "4001"
      S3_BUCKET: "source"
